name: Reusable Workflow for Clober DEX

on:
  pull_request_target:
    types: [opened, edited, reopened]
  push:
    branches:
      - '**'

# Action should have write permission to make updates to PR
permissions:
  pull-requests: write

jobs:
  clober-template:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          body-regex: '.{10,}'
          body-fail: true
          body-comment: 'Please provide a description of your PR.'
          title-check-enable: false
      - uses: webiny/action-conventional-commits@v1.1.0